### ISSUE TITLE
Incompatible with Nixpkgs master (LTS Haskell 10.0)

### ISSUE THREAD

**Issue by orivej** [pbogdan/nix-derivation-pretty#5]
It needs to bump versions of these by 0.1:
```
base >=4.9.0.0 && <4.10,
optparse-applicative >=0.13.2 && <0.14,
protolude >=0.1.10 && <0.2
```
but also some code changes that I could not do.

**Comment by pbogdan** [comment]
Thanks @orivej, I'll try to take a look this weekend.

**Comment by pbogdan** [comment]
I believe latest master should be good now - could you give it a try?

**Comment by orivej** [comment]
It works, thank you!

**Comment by pbogdan** [comment]
Great, thank you for testing and reporting the issue :-)
