### ISSUE TITLE
bash completion

### ISSUE THREAD

**Issue by sboosali** [pbogdan/nix-derivation-pretty#8]
Following the instructions at https://github.com/pcapriotti/optparse-applicative/wiki/Bash-Completion:

```
source <(pp-drv --bash-completion-script `which pp-drv`)
```

, the default / automatically generated autocompletion works:

```
$ pp-drv --<TAB>
--haskell  --help     --human    --width 

```

, with this in a `.bashrc`:

```
source ~/.nix-profile/etc/bash_completion.d/*   
```

or manually sourced similarly.

**Comment by sboosali** [comment]
I don't know much about bash completions, but adding this hook to `nix-derivation-pretty.nix`:

```
mkDerivation {
  ...
  postInstall = ''
    EXECUTABLE_NAME="pp-drv"
    PROGRAM="$out/bin/$EXECUTABLE_NAME"

    COMPLETION_DIRECTORY="$out/share/bash-completion/completions"
    COMPLETION_FILE="$COMPLETION_DIRECTORY/$EXECUTABLE_NAME"

    mkdir -p "$COMPLETION_DIRECTORY"
    $PROGRAM --bash-completion-script $PROGRAM > "$COMPLETION_FILE"

    echo "wrote bash-completion to $COMPLETION_FILE"
  '';
}
```

seems to work. Confirming the installation with

```
  $ find ~/.nix-profile/share/bash-completion/completions/ | grep pp-drv
  /home/sboo/.nix-profile/share/bash-completion/completions/pp-drv
```

and its behavior:

```
  $ pp-drv --<TAB>
  (nothing printed)
  $ source ~/.nix-profile/share/bash-completion/completions/pp-drv
  $ pp-drv --h<TAB>
  --haskell  --help     --human    
```

obviously, we should modify it in default.nix, so that `nix-derivation-pretty.nix` can still be automatically generated. But it seems to work.

**Comment by pbogdan** [comment]
Oh, nice, thank you! Somehow I never realised `optparse-applicative` could do this. Not that I know much about how completion works but I pushed few commits to master to have them included in the package and work for completing the "file" argument. Things look to be working in `zsh` for me, `bash` completion is included too but let me know if anything isn't working for you.

**Comment by sboosali** [comment]
the bash completion works for me. thanks for the promptness!

**Comment by pbogdan** [comment]
Great! Thank you for checking and for the suggestion :-).
